language: node_js
node_js: 13.11.0
os: osx
osx_image: xcode11.3
git:
  depth: false
  quiet: true
jobs:
  include:
    - stage: unit-test
      script: yarn test src
    - stage: build
      script: yarn electron-build
    - stage: e2e-test
      script: yarn test e2e

stages:
  - unit-test
  - build
  - e2e-test

branches:
  only:
    - master